### ISSUE TITLE
こどふぉブログに宣伝記事を書く

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#111]
レートが高い人が書いた方が †効く† ので @beet-aizu に任せたさがある

**Comment by kmyk** [comment]
@beet-aizu お願いします :pray: :pray: :pray:

**Comment by beet-aizu** [comment]
とりあえず赤に戻したらドキュメント書いてやります

**Comment by kmyk** [comment]
ありがとう

**Comment by kmyk** [comment]
https://codeforces.com/blog/entry/74013
感謝
