### ISSUE TITLE
コミット権限の整理

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#141]
いま @beet-aizu @tsutaj に付与してある。
付与しても特になにかが減るわけではないが、必要がないなら無闇に渡すべきではない。

特に @tsutaj について、使ってないようだしひとまず無効にしておこうと思う。よいですか？

**Comment by tsutaj** [comment]
大丈夫です、今後またなにか commit したいものができたら PR します

**Comment by kmyk** [comment]
@tsutaj 了解です。ではいったん無効化しておきます。
権限がほしくなる機会 (たくさん機能を足したい、就活でOSSメンテナを名乗りたい、…) などがあれば、要求してもらえればまた付与します。

**Comment by kmyk** [comment]
無効化した
