### ISSUE TITLE
TLEの設定

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#147]
60秒でハードコーディングされているがsanitizeをつけたらTLEしたので環境変数を見るようにしたい
https://github.com/beet-aizu/library/runs/446375370?check_suite_focus=true

**Comment by kmyk** [comment]
制限時間の設定をできるようにするのはよさそう。
ところで、実装するとして選択肢は 3 通りあります。個人的には (2.) の実行時オプションがよい気がしています (環境変数は基本的に認証情報 + `CXXFLAGS` みたいな有名変数を使うもので、そうでないなら `--help` で説明がでてくるオプションの方がうれしい)

1. 環境変数
2. 実行時オプション
3. ファイルごとの設定 (`ERROR` とかと同じ感じで)

**Comment by beet-aizu** [comment]
オプションで実装します

**Comment by beet-aizu** [comment]
#155
