### ISSUE TITLE
cache について

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#16]

**Comment by kmyk** [comment]
https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows#using-the-cache-action こういうのをうまく使うとわざわざpushとかしなくてもよくなったりしないでしょうか？(偶然見つけただけなので、全然違うものかもしれないです)

_Originally posted by @yosupo06 in https://github.com/kmyk/online-judge-verify-helper/issues/1#issuecomment-559682589_

**Comment by kmyk** [comment]
#4 にも議論がある (verified でなくして再実行させるための操作がほしいという話)

**Comment by kmyk** [comment]
> cacheの話です

ローカルに持ってくること考えるとpushしたい気持ちになりますが、そもそもキャッシュがよくわからないためどっちがいいのかすらよくわからない

_Originally posted by @beet-aizu in https://github.com/kmyk/online-judge-verify-helper/issues/1#issuecomment-559692106_

**Comment by kmyk** [comment]
選択肢:

 -  `test/{.test.cppのpathなどのmd5sum}` という名前のファイルを作ってタイムスタンプで管理し自動で commit し push
    -   現状はこれ
    -   md5 だとどのファイルがどれだか分からなくてつらい
    -   削除がないので無限にたまっていきそう
-   `cache.remote.json` みたいなファイルに分かりやすい形式で保存して自動で commit し push
    -   分かりやすい
    -   branch を切るとめちゃくちゃ衝突しそう
    -   local のキャッシュと混ぜると pull するだけでも衝突しそう
-   cache アクションの利用
    -   よさそう
    -   データの格納形式は別途考えないとだめ
    -   複数 branch のしんどさはましだが別の形で残る (全 branch で共通にすると古い branch に移動したときに時間遡行があるので壊れるが、branch ごとだと branch を切るたび全部実行しなおしになる)
    -   cache 内容の中身を見るのは面倒そう

**Comment by kmyk** [comment]
1 ファイルにまとめるのがよさそう (消去法)

- cache アクションだと timestamp が push されなくて、そうだとするとドキュメント生成のときにも困るのでよくない (https://twitter.com/beet_aizu/status/1200372712285200391, https://github.com/kmyk/online-judge-verify-helper/pull/18#issue-347110131)
- 現状の方式は面倒だしよくない

---

`.verify-helper/cache.local.json` および `.verify-helper/cache.remote.json` に次の形式で保存するのがよさそう。失敗したら対応するファイル名は json 中から消すようにしたい。

```json
{"test/segment_tree.yosupo.test.cpp": "2019-11-29T16:08:25+09:00", "test/union_find.aoj.test.cpp": "2019-11-29T16:08:25+09:00", ...}
```

根拠など:

-   読み書きしやすいので json を使う。txt に雑に並べたり csv とかは仕様が訳分からなくなってバグる、yaml や toml は複雑すぎて使いにくい
-   local と remote の cache は分ける。分けないと git pull とかで conflict が起こる
-   g++ でテストしたか clang++ でテストしたかの情報を細かく持つ必要はないので捨てる。どちらかが失敗したらそれは半分成功ではなくて失敗なので
-   とりあえず `.verify-helper/` に入れておく。`test/` だと、すでにその名前のディレクトリを使ってる人がいそうだし、あまり触っちゃいけない感がでないのでうっかり json を壊して動かなくする人がでてくる

**Comment by kmyk** [comment]
@beet-aizu このキャッシュのやつ任せていいですか？ よろしくお願いします :pray:

**Comment by beet-aizu** [comment]
>     * local と remote の cache は分ける。分けないと git pull とかで conflict が起こる
localでCI回すことはないとしてよくないですか？　つまり、timestamp.json 一つにしたいんですが

**Comment by kmyk** [comment]
local で CI を回すことはなくても local で `oj-verify` を実行することはあるので、だめです。書いたコードを commit して push する前に local で動作確認したいからです。submit debug はあまり行儀のよいものではない。
そして local と remote で cache が分かれていないと、local での動作確認が conflict だらけで大変になります。

**Comment by beet-aizu** [comment]
動作確認したいだけならgit stashで戻せばいいだけだと思うんですけど（迷推理）

**Comment by kmyk** [comment]
それが面倒でつらいでしょという主張で、ファイルを分けるだけで解決するのだからファイルを分けて解決したい

**Comment by beet-aizu** [comment]
これ考えれば考えるほど意味不明なんですがlocalとremoteの同期は手動でやるってことですよね？それこそ面倒だと思うんですけど

**Comment by kmyk** [comment]
いいえ、そもそも同期はしない想定です (local と remote はコンパイラのバージョンなどの環境が異なっていて、その verify 結果を混ぜるべきでないため)

**Comment by beet-aizu** [comment]
えーまあ僕はその機能を使うことはないと思うんですが使いたいという人がいるのならOKです
