### ISSUE TITLE
verification of AWK codes in this repository fails on Mac

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#167]
INFO:onlinejudge_verify.main:generate documents...
sed: 1: "s/^@include "\(.*\)"$/\ ...": undefined label '; d'

**Comment by kmyk** [comment]
sed ってことはこの辺の AWK の影響ぽい。よくないけど他にも C# script のための `dotnet` コマンドが入ってないと落ちるし、そのうち Rust や Python 関連でも同様の問題で落ちるようになるはずで、わりとどうしようもなさある。例外を拾って :x: を付けるようにしたい

https://github.com/kmyk/online-judge-verify-helper/blob/119196c7483b9427b9faca1512d378b7be03b62e/.verify-helper/config.toml#L1-L6
