### ISSUE TITLE
installer.htmlの修正

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#169]
多分Github Pagesそのものの設定も必要
https://help.github.com/ja/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by kmyk** [comment]
@beet-aizu これどういうことですか？
`gh-pages` branch を作れば自動で設定されるはずです。実際、そのページの一番上にも

> GitHub Pages サイトでデフォルトの公開元を使用している場合、サイトは自動的に公開されます。 プロジェクトサイトを、別のブランチやフォルダから公開するよう設定することも可能です。

って書いてあります。

**Comment by beet-aizu** [comment]
デフォルトの公開元、masterじゃないかと思っています
https://github.com/beet-aizu/online-judge-verify-helper が「公開元を選択する」の3. をしないと公開されませんでした

**Comment by kmyk** [comment]
そんなことないと思うんだけどなあ (fork したリポジトリについては特殊だったりするのかも？)

こういうときは最近ドキュメント生成機能を設定した人に聞けばよいですね。
@key-moon @knuu @maspypy ドキュメント生成を動かすために[GitHub Pages サイトの公開元を設定する - GitHub ヘルプ](https://help.github.com/ja/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)に書かれているような操作は必要でしたか？

**Comment by knuu** [comment]
私はいじった記憶がないです

**Comment by maspypy** [comment]
GitHub Pagesそのものを使うために何かしらの選択はしました（Themeを適当に選ぶ、くらいかな？）が、公開元をいじるようなことはしていないです。デフォルトのSourceは、gh-pages branchでした。

**Comment by beet-aizu** [comment]
新しいレポジトリを作ったら想定通りの挙動をしました　forkがいけないのかな
https://github.com/beet-aizu/gh_pages_test

**Comment by beet-aizu** [comment]
ログを確認したんですが結論から言うと僕の勘違いでした 🙇 

備忘録として勘違いの原因を書いておくと
動いていない状態から
https://github.com/beet-aizu/online-judge-verify-helper/runs/462147922

テーマを設定すると動くようになって
https://github.com/beet-aizu/online-judge-verify-helper/commit/8840805eb12bfe904b689d5ed2076328b2ec7230

このタイミングでGH_PATを設定したのでテーマ関係の何かがトリガーだと勘違いしました
https://github.com/beet-aizu/online-judge-verify-helper/runs/462158743

**Comment by key-moon** [comment]
closedなところ申し訳ないんですが、自分の場合は昔作ろうと思って放置していたgithub.ioリポジトリの/libraryと衝突して生成されませんでした(消去したら出ました 流石にここまでカバーするのはやりすぎだと思うのでヘルプとかもいらないとは思いますが)
