### ISSUE TITLE
yosupo judge の checker対応

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#19]
> > https://judge.yosupo.jp から testlib.h 形式のジャッジプログラムを拾ってきて自動で利用してほしい
> 
> とりあえずは `oj` のライブラリ部分の機能として対応し (コマンドとしては足すかどうかは後回しにしたいので)、その呼び出しはこっちでやるのがいいかなと思っています

これoj t --yosupo "問題名" とかにしてしまいたいです（コード読んだ感じojの中にhttps://github.com/yosupo06/library-checker-problems をgit cloneしてきているんですよね？

_Originally posted by @beet-aizu in https://github.com/kmyk/online-judge-verify-helper/issues/1#issuecomment-559909345_

1. checker.cpp をレポジトリから持ってくる　このときディレクトリを特定するのにproblems.tomlを読む必要がある

2. checker.cpp をコンパイルする　実行ファイルをどこに置くかは考える必要がありそう
- ojを実行したディレクトリ　衝突するかも？（checkerなんて置いておくことあるか？）
- ojの内部　まあこっちかなあ

3. oj t --judge-command を呼ぶ

yosupoジャッジでcheckerを使わない問題は今の所ないのでこの一連の操作をコマンドにしてしまった方が楽な気がします

**Comment by beet-aizu** [comment]
あー違うのか　download時にcheckerの実行ファイルを生成してしまってoj t --judge-command を呼ぶようにするべきっぽいな

メモ：
https://github.com/kmyk/online-judge-tools/blob/e0dc4073546fc7ec67398dd90ef78e1c0209bdea/onlinejudge/_implementation/command/download.py#L29

https://github.com/kmyk/online-judge-tools/blob/e0dc4073546fc7ec67398dd90ef78e1c0209bdea/onlinejudge/_implementation/command/test.py#L194

https://github.com/kmyk/online-judge-tools/blob/e0dc4073546fc7ec67398dd90ef78e1c0209bdea/onlinejudge/service/library_checker.py#L60

**Comment by beet-aizu** [comment]
https://github.com/kmyk/online-judge-tools/blob/e0dc4073546fc7ec67398dd90ef78e1c0209bdea/onlinejudge/service/library_checker.py#L52　に「checkerをコンパイルして配置する」処理を追加すればいい？

**Comment by beet-aizu** [comment]
カスなんですが checker.outを吐けば　https://github.com/kmyk/online-judge-tools/blob/e0dc4073546fc7ec67398dd90ef78e1c0209bdea/onlinejudge/_implementation/command/download.py#L56　はそのままでいいな！

**Comment by kmyk** [comment]
とりあえず一番変更量が少なくなる感じでプルリクしておきました。オプションやコマンドを増やそうとるすと仕様に関する議論をしたりテストを書いたりがする必要がでてくるためです
https://github.com/kmyk/online-judge-tools/pull/624

**Comment by beet-aizu** [comment]
プロプロプロプロ

**Comment by beet-aizu** [comment]
これ https://github.com/kmyk/online-judge-tools/blob/7ecb2f48f9956ae166ccacdd129a01f0cae26872/onlinejudge/service/library_checker.py#L68 の出力先がstdoutなせいでこわれている気がします

**Comment by kmyk** [comment]
あー、なるほど :bow:
そこを両方 stderr に出すプルリクを投げるか、`python3 -c 'import onlinejudge, sys ; open("hoge", "wb").write(onlinejudge.dispatch.problem_from_url("https://judge.yosupo.jp/problem/unionfind").download_checker_cpp())'` して回避するか、`test.sh` 全体を Python で書き直すかのどれかをお願いします

**Comment by beet-aizu** [comment]
二つ目の方法にしました

**Comment by kmyk** [comment]
ドキュメント生成器が judge.yosupo.jp のための `test/9cee1c300646c09ec8db07886051a645/testlib.h` を巻き込んでしまってたのでとりあえずディレクトリを移しました。
@beet-aizu なにもしなかったらすべて verify しなおしです。必要なら `mv test .verify-helper` とか実行してください

``` python
INFO:onlinejudge_verify.main:generate documents...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.0/x64/bin/oj-verify", line 11, in <module>
    load_entry_point('online-judge-verify-helper==2.0.2', 'console_scripts', 'oj-verify')()
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/onlinejudge_verify/main.py", line 124, in main
    subcommand_docs()
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/onlinejudge_verify/main.py", line 107, in subcommand_docs
    onlinejudge_verify.docs.main(html=False)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 528, in main
    builder = PagesBuilder(cpp_source_path='.', config=config)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 364, in __init__
    self.build_library_files(cpp_source_path, md_destination_path)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 480, in build_library_files
    page.build(self.path_to_title, self.path_to_verification, category, categorize_library_cond)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 245, in build
    self.write_contents(file_object, path_to_title, path_to_verification)
  File "/opt/hostedtoolcache/Python/3.8.0/x64/lib/python3.8/site-packages/onlinejudge_verify/docs.py", line 199, in write_contents
    mark = self.get_mark(path_to_verification[depends])
KeyError: 'test/9cee1c300646c09ec8db07886051a645/testlib.h'
##[error]Process completed with exit code 1.
```

**Comment by kmyk** [comment]
これ終わってるぽいので閉じておきます
