### ISSUE TITLE
#define IGNOREしてるのにページが生成される

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#198]
https://beet-aizu.github.io/library/library/leetcode/treenode.cpp.html
前は消えてたはず

**Comment by kmyk** [comment]
仕様です。以前の挙動は不適切かつ undocumented だったので修正されました (「テストを実行しない」の意味の "ignore" と「ドキュメントを生成しない」の意味の "ignore" を混同してるのはやばいだろ)
