### ISSUE TITLE
HTML Build の仕様

### ISSUE THREAD

**Issue by tsutaj** [kmyk/online-judge-verify-helper#2]
※もともと [TODO](https://github.com/kmyk/online-judge-verify-helper/issues/1#issuecomment-558470582) へのリプライとして書いていましたが、長くなりそうなので分離しました

> * `#define DESCRIPTION` などを定義させるよりも Doxygen 記法のコメント
> ([例1](https://github.com/ferin-15/program_contest_library/blob/3c915b07f170e47a1420499a5da3ec023bc50cab/oldcode/parallel_binary_search.cpp#L44-L48), [例2](https://github.com/kmyk/competitive-programming-library/blob/master/graph/lowest_common_ancestor.hpp#L9-L13)) を書かせてそれを解析する方が適切そうに見える。説明を 1 行で書くのはしんどいし、かといって path を指定させて別ファイルに書かせるのはもっと手間なので。もちろん実装はマクロの方が楽なので開発リソース次第ですが……

これは確かにそうですね、そういう仕様にしたいと思います。
だいたいのもの (URL や簡単な問題概要など) は 1 行で書けると思うためそれで良いと思うのですが、Docs に関しては外部ファイルへのパスを記述したほうがいいかなと思っています。

例: https://tsutajiro.github.io/cpp_library/library/strc_024_static_wavelet_matrix.cpp.html  
(これの、タイトルの後から「Requires」の前までは全部 Docs です)

パスを書く利点としては
- ファイルが分かれていると、Docs 部分のみの Markdown Preview がしやすい (Atom 等で Docs だけ編集するケースなどを想定しています)
- コード本体に大きな影響を及ぼさない

などがあるかなと思っています。  
(https://qiita.com/inabe49/items/23e615649e8539d857a8 のように各関数に対する Docs をパースできれば本体に書いてもいいのかもしれませんが・・・)

**Comment by kmyk** [comment]
外部ファイルについて、使わない方法はやはりほしいけれど、使う方法もあってほしい気がしてきました。

-   > ファイルが分かれていると、Docs 部分のみの Markdown Preview がしやすい (Atom 等で Docs だけ編集するケースなどを想定しています)

    これ気づいてなかったけど説得力ある
-   > コード本体に大きな影響を及ぼさない

    これってつまり「ドキュメント書き換えだけなのにCIが走るみたいなことがない」で、これもうれしそう
-   足すとしても `#define DOCS` での指定はやめたい。Doxygen 風の独自コマンドなどで `@docs ./docs/strc_024_static_wavelet_matrix.md` とか書く感じにしたい (`.hpp` を書いて include したときに意味が分からなくなるので)

**Comment by Tsutajiro** [comment]
> 足すとしても #define DOCS での指定はやめたい 

これは自分もそう思うので、`#define` であれこれ指定するのは撤廃して、`@command` の形式に統一しようと思います。現状の設計の予定は https://github.com/Tsutajiro/cpp_library/issues/4#issue-528417319 に書いておきましたので、何かありましたらツッコミ入れていただけるとありがたいです。

**Comment by kmyk** [comment]
ところで `build-pages.py` について、このリポジトリにプルリクを出すのでなくて、「競プロライブラリからドキュメントを作る (それ専用の) ツール」として作る (そしてこちらはそれが自動で導入されるような設定をする) という選択肢もある気がしてきました。(もちろんプルリクを出してもらってもよくて、好きな方を選んでください)

**Comment by kmyk** [comment]
GitHub Pages が前提なら GitHub 上のページに飛ぶボタンがほしいな

**Comment by beet-aizu** [comment]
もしかしてライブラリがライブラリに依存してるとうまく動かなかったりしますか？　（エラー吐いて死にました　https://github.com/beet-aizu/library/commit/b37f176ae180c8eed89a66a7b249bfddb555fa84/checks?check_suite_id=343370203

**Comment by beet-aizu** [comment]
多分ここっぽい　
https://github.com/kmyk/online-judge-verify-helper/blob/e16dfe14f63f360c92a6538302f6c1cf2aa021a3/onlinejudge_verify/docs.py#L472

test.cpp以外が依存していることもあります　参考：
https://github.com/beet-aizu/library/blob/master/linkcuttree/path.cpp

**Comment by beet-aizu** [comment]
あとここってどうやって書き換えることを想定していますか　https://github.com/kmyk/online-judge-verify-helper/blob/e16dfe14f63f360c92a6538302f6c1cf2aa021a3/onlinejudge_verify/docs.py#L537

**Comment by beet-aizu** [comment]
dictのgetを使うようにすればエラーは消せそうですが、実装の意味論がどうなるかよくわかりません…

**Comment by kmyk** [comment]
> もしかしてライブラリがライブラリに依存してるとうまく動かなかったりしますか？　（エラー吐いて死にました

修正できるのならとりあえず修正してしまってよいと思います (本当か？)。実装の細かいところは私もよく分かっていません 。
@tsutaj たすけて

> あとここってどうやって書き換えることを想定していますか

たぶんそのうち `.verify-helper/docs/config.json` みたいなファイルが作られてそこを読みにいくようになるのだと思っています

**Comment by tsutaj** [comment]
@beet-aizu key が存在していなくて落ちているようですね、確かにそのようなケースは現在未対応ですので、`cpp` が別の `cpp` に依存しているのもケアするように直します

`description` 等に関しては kimiyuki さんの言うとおり `config.json` のようなものを読みに行く方針にこれから変えていきたいと思います

**Comment by tsutaj** [comment]
一応 `cpp` が `cpp` に依存している場合は、依存元に以下のように書くと動くはずです

```
// @depends [依存先の相対パス]
```

ただ、#include しているものがそのまま反映されないのは不便なのでいずれにせよ直します

**Comment by tsutaj** [comment]
色々直して、とりあえず手元で https://github.com/beet-aizu/library と https://github.com/kmyk/competitive-programming-library の Docs ビルドが動きそうなことは確認しました。
config が編集できるようにしたい問題はもう少し待ってください

**Comment by beet-aizu** [comment]
落ちました😭　https://github.com/beet-aizu/library/runs/339268631

**Comment by beet-aizu** [comment]
これ　vector<num> rts={{0,0},{1,0}}; で落ちてますね（コードもエスケープしないとダメそう？

**Comment by beet-aizu** [comment]
これか　https://github.com/kmyk/online-judge-verify-helper/issues/27#issuecomment-562470527

**Comment by tsutaj** [comment]
https://github.com/kmyk/online-judge-verify-helper/commit/c493fdb6cc1b2894c1dea8dfb5ce088f99f304c6 にて直しました
バージョンも上げましたので再度ビルドしてみてください

**Comment by tsutaj** [comment]
あと Jekyll のテーマが何も設定されておらず若干寂しかったので、デフォルトで `minima` https://github.com/jekyll/minima を採用することにしました

**Comment by beet-aizu** [comment]
minima だと落ちました　https://github.com/beet-aizu/library/runs/339464950
jekyll-theme-minimal だと通ります（なんで？　https://github.com/beet-aizu/library/runs/339457351

**Comment by tsutaj** [comment]
minima、なぜかビルドに時間かかるのでタイムアウトしてますね・・・
別のテーマをデフォルトにするようにします

**Comment by beet-aizu** [comment]
あ、デバッグしたくてminima 消しちゃいました（すみません）　気にせず変更していただいてOKです👍

**Comment by tsutaj** [comment]
デフォルトのテーマを Dinky にしました ( 参考？: https://github.com/kmyk/online-judge-verify-helper/issues/28#issuecomment-563125475 )

手元で beet さんのリポジトリで `bundle exec jekyll build` してみたら 12 sec くらいで終わったので、おそらく大丈夫かと・・・
