### ISSUE TITLE
生成に失敗したTimestampのパースに失敗する

### ISSUE THREAD

**Issue by key-moon** [kmyk/online-judge-verify-helper#206]
何らかの原因でTimestampが上手く生成されないと`"1970-01-01 00:00:00 "`みたいなタイムスタンプが出てきて次回のパース時に死ぬ [ログ](https://github.com/key-moon/Library/runs/447841239?check_suite_focus=true),[verify-commit](https://github.com/key-moon/Library/commit/4995d082bb2a5409629ae9b3979f1567585c41c2#diff-08ada8ce32c90710be31d822289decf9)

**Comment by kmyk** [comment]
verify helper 本体のバグっぽい。頻発するならかなりやばい。
しかし timestamp 生成失敗してるのは古いバージョンである + 検索をかけた限り key-moon/Library しか見つからなかったため、原因不明だしとりあえず様子見します。
<https://github.com/search?q=1970+path%3A.verify-helper&type=Code>

**Comment by key-moon** [comment]
verifyしたファイルのタイムスタンプ取得に失敗した時にフェイルセーフで`0`を指定しているところが直接の原因のようです。

https://github.com/kmyk/online-judge-verify-helper/blob/172f602239711e7f316ed6f913b678a16189b430/onlinejudge_verify/marker.py#L133

タイムスタンプ取得に失敗するのは`(`,`)`のような特殊文字の扱いで失敗しているからに見えます。

https://github.com/key-moon/Library/blob/master/.verify-helper/timestamps.remote.json

**Comment by kmyk** [comment]
デバッグのプロ
直します
