### ISSUE TITLE
GitHub Actionsでテストしたくないファイルがテストされてしまう

### ISSUE THREAD

**Issue by knshnb** [kmyk/online-judge-verify-helper#228]
C++で、
- `.test`がファイル名に含まれていないファイルがテストされる(https://github.com/knshnb/competitive_library/runs/621356389?check_suite_focus=true)
-  `#define IGNORE`されているファイルがテストされる(https://github.com/knshnb/competitive_library/runs/620332379?check_suite_focus=true)

自分の設定ミスだったらすいません。

**Comment by kmyk** [comment]
具体的に commit hash とファイル名を書いてほしい

**Comment by kmyk** [comment]
テストがされてるのでなくて、依存関係の解析をするフェイズで落ちてるように見えます。
どのファイルがどのファイルに依存してるかや `#define IGNORE` されてるかどうかは、とりあえず一度 g++ でコンパイルしてみることで判断しています。たぶんこのときコンパイル不可能なコードに対するエラー処理をしてない (†バグ†) はずで、こんなことになっています。

**Comment by kmyk** [comment]
#197 と重複

**Comment by knshnb** [comment]
@kmyk 
ありがとうございます。

https://github.com/knshnb/competitive_library/runs/618276854?check_suite_focus=true
ここに書くべきでは無いかもしれませんが、そもそもこれがコンパイル通っていない原因もわかっていません(テストで落ちるのでとりあえずファイルをignoreしたりファイル名変更して対応しようとした結果が先程のissueです)。

手元のMac環境では`oj-verify run`は通っていて、依存関係は特に問題ないように思えるのですが…
(問題ファイル: https://github.com/knshnb/competitive_library/blob/e4a8328a5afcafb5a4604fbb9fe781df8b4a9e0c/test/yukicoder/1036_segment_tree.test.cpp)

**Comment by kmyk** [comment]
include は `#include "../../src/Datastructure/SegmentTree.hpp"` ですが、実際にあるファイルは `src/DataStructure/SegmentTree.hpp` です。`DataStructure` の `S` の小文字と大文字が違います。Windows ではファイル名の大文字小文字は無視されますが、Linux や Mac OS では区別されるので、この差が疑われます。

https://github.com/knshnb/competitive_library/blob/e4a8328a5afcafb5a4604fbb9fe781df8b4a9e0c/test/yukicoder/1036_segment_tree.test.cpp#L18
https://github.com/knshnb/competitive_library/blob/e4a8328a5afcafb5a4604fbb9fe781df8b4a9e0c/src/DataStructure/SegmentTree.hpp

**Comment by knshnb** [comment]
完全に自分の確認不足でした…ありがとうございます。

**Comment by kmyk** [comment]
これは知らないと確認のしようもない罠だし、仕方なさそう
