### ISSUE TITLE
docs のパス処理

### ISSUE THREAD

**Issue by tsutaj** [kmyk/online-judge-verify-helper#26]
`os.path.relpath` ではなく、極力絶対パスで処理したい。つまり `os.path.abspath` を使う形に変えたい

**Comment by tsutaj** [comment]
関連する報告
* https://github.com/kmyk/online-judge-verify-helper/issues/25#issue-530559669
* https://github.com/kmyk/online-judge-verify-helper/pull/20

**Comment by tsutaj** [comment]
`deployed_assets` のパス周りの処理もおかしそう (実際に生成されたファイルを見ると、相対パスが合っていない)

**Comment by kmyk** [comment]
どうせ書き直すなら `pathlib` を使うのがおすすめです
https://docs.python.org/ja/3/library/pathlib.html
