### ISSUE TITLE
ソースコード中に {{{ や }}} のような文字列があると GitHub Pages が更新されない

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#27]
Jekyll のあたりのなにかの影響です

**Comment by tsutaj** [comment]
Jekyll が内部で使用している Markdown レンダラーが kramdown なのですが、多分コレのせいです。

`{% raw %}` と `{% endraw %}` で囲むといいらしい？ https://stackoverflow.com/questions/3426182/how-to-escape-liquid-template-tags
試してみます

**Comment by tsutaj** [comment]
https://github.com/kmyk/online-judge-verify-helper/commit/c493fdb6cc1b2894c1dea8dfb5ce088f99f304c6 で対応しました、すみません 
beet さんのビルドがうまくいったら閉じます

**Comment by tsutaj** [comment]
これに起因するビルド失敗は解消されたと思うので閉じます
