### ISSUE TITLE
test.sh を Python で書き直す

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#29]
verify 関連でどんな機能を追加するにしてもまずこれをしないと始まりません。速度優先をやって泥沼にはまりました。まさに技術的負債って感じがする

**Comment by kmyk** [comment]
push する部分を Python に移しました。ちょっとだけ修正のはずがかなりしんどかったです

**Comment by kmyk** [comment]
@tsutaj が必要に迫られてちょっとずつ shellscript 部分 Python に移植するやつをやってくれてるので流用するとよさそうな感じ (例: https://github.com/kmyk/online-judge-verify-helper/commit/93eb90d68d21b7cc9da4bdc0fb978ea5881c995a )

**Comment by tsutaj** [comment]
このへんの関数ってファイル分けてモジュール化したほうがいいですか？
というか `docs.py` もあとあとファイルを分けるつもりでクラスに分けたりしていたのに速度重視で無視していたらめちゃくちゃ長いコードになってしまった・・・

**Comment by kmyk** [comment]
このあたりの関数もいまはまだ `docs.py` からしか使ってないので、このままで何も問題ないと考えています。もちろんいつかはファイルを分けることになると思います。
`docs.py` も特にファイルの分割はいらないはず (これは単に私の好みでしかないのですが、常に同時に使われるクラスを別々のファイルに分けて書いてもむしろ読みにくくなるだけだと感じています)

**Comment by kmyk** [comment]
開発のコードの長さですが、800行ほどで型やコメントがあるきれいに書かれたコードなら十分短いので気にしなくてよい、3000行だと長いけどわりとある、10000行を超えるのは見かけないのでそれぐらいが限界、という印象です。

**Comment by tsutaj** [comment]
なるほど参考になります、では必要に迫られたら分離するということで、いまはこのままにしておきます

**Comment by kmyk** [comment]
頑張っています

**Comment by kmyk** [comment]
@beet-aizu Python での再実装、私の代わりにやりませんか？
#16 #49 などをする前段階として必要です
もちろん私がやってもいいんですが、途中であと 1, 2 回くらいは CI が破壊されてしまうと思うので…… (最悪)

**Comment by beet-aizu** [comment]
#16 はやりたいのでやります　時間かかるかもですが

**Comment by beet-aizu** [comment]
is-verified() と mark-verified() をPython側に持ってくる

https://github.com/kmyk/online-judge-verify-helper/issues/16#issuecomment-559949301
ではjsonになっているが_config.yml に合わせてyml形式の方がよさそう？

タイムスタンプを最初から破壊するよりは（タイムスタンプ + yml形式）にしてドキュメント生成側でymlに対応してから破壊した方が移行がスムースになりそう

**Comment by kmyk** [comment]
> https://github.com/kmyk/online-judge-verify-helper/issues/16#issuecomment-559949301 ではjsonになっているが_config.yml に合わせてyml形式の方がよさそう？

この意見も間違いではないですが、json がうれしいです。
主に人間が触るものは yaml や toml にしたいですが、主にプログラムが触るものは json がよい。json と比べて yaml は構文がかなり複雑で闇 (内部で変数みたいなものが使えたりする) だし検索や操作がしにくい (たとえば json なら [jq](https://stedolan.github.io/jq/) があるが yaml にはない) ためです

**Comment by kmyk** [comment]
json は改行を工夫するとよくて、たとえば以下のように入れると GitHub 上の diff などもきれいになってうれしいです

``` json
{"test/segment_tree.yosupo.test.cpp": "2019-11-29T16:08:25+09:00"
,"test/union_find.aoj.test.cpp": "2019-11-29T16:08:25+09:00"
,"test/segment_tree.yosupo.test.cpp": "2019-11-29T16:08:25+09:00"
,"test/union_find.aoj.test.cpp": "2019-11-29T16:08:25+09:00"
,"test/segment_tree.yosupo.test.cpp": "2019-11-29T16:08:25+09:00"
,"test/union_find.aoj.test.cpp": "2019-11-29T16:08:25+09:00"
,"test/segment_tree.yosupo.test.cpp": "2019-11-29T16:08:25+09:00"
,"test/union_find.aoj.test.cpp": "2019-11-29T16:08:25+09:00"
}
```

**Comment by beet-aizu** [comment]
https://github.com/kmyk/online-judge-verify-helper/blob/master/.verify-helper/timestamp/timestamp.json 動いたと思います
