### ISSUE TITLE
テストするファイル数の上限

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#3]
https://github.com/kmyk/online-judge-verify-helper/blob/7156fbdc960360e8c4260017d0ada617c075798d/data/test.sh#L49

ここ20件固定じゃなくて設定できるようにしたい／単純に時刻でソートするだけだと埋もれるファイルができうる気がします。

**Comment by kmyk** [comment]
この制約は、毎回全部テストするとファイル数 N に対しコミットごとに O(N) になってつらいから無理矢理 O(20) にするための嘘解法的なものです。キャッシュが入ればコミットごとに均し O(1) になるので、この制約はまったく消してしまうことができます。

**Comment by kmyk** [comment]
キャッシュが入ったのでもう気にしなくてよい
