### ISSUE TITLE
docsのアイコンがおかしい

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#31]
https://kmyk.github.io/online-judge-verify-helper/library/examples/macros.hpp.html
のアイコンが :warning: になっている（トップページでは :heavy_check_mark: になっている）

**Comment by tsutaj** [comment]
報告どうもです、なおしました https://github.com/kmyk/online-judge-verify-helper/commit/4ccbb9c66f47429e3c3b4adf07b6cd4e94cc8d90
