### ISSUE TITLE
ライブラリ一覧ページのリンクを分かりやすくする

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#33]
ライブラリ一覧ページ (https://kmyk.github.io/online-judge-verify-helper/ ) のリンクを ` examples/segment_tree.hpp` などのファイル名そのままでなく `セグメント木` みたいな名前にしたいです (イメージ: http://www.prefield.com/algorithm/ )。たぶん `@brief` を (もしあれば) それをそのまま使えばよさそう

**Comment by tsutaj** [comment]
実はその機能はもう存在します、 `@title [タイトル]` または `@file [タイトル]` と書くとそれがタイトルとして採用されます (指定がない場合はファイル名、複数指定されている場合は最後に指定された要素)

同様に `@category` というものもあって、これでカテゴリを定義できます (指定がない場合はディレクトリ名)

demo: https://tsutaj.github.io/cpp_library/#%E3%82%BB%E3%82%B0%E3%83%A1%E3%83%B3%E3%83%88%E6%9C%A8-segment-tree

テストしてみて不具合あったら教えてください

**Comment by kmyk** [comment]
これまじ？ すごい :beet:

**Comment by tsutaj** [comment]
ドキュメントの必要性を感じますね・・・ (TODO まだ消化してないし仕様もそこまで固まってないのでまだなにも書いていない)

**Comment by kmyk** [comment]
しかしやはり独自コマンド `@title` を定義するより標準のもの `@brief` を流用したいように思います。
理由はふたつです: (1) どうせ要約説明である `@brief` は書くだろうのでまとめられると使うのが楽、(2) 標準の記法ならユーザはなんとなく使い方が分かるので我々がドキュメントをきっちり書かなくてよくてうれしい
http://www.doxygen.jp/commands.html#cmdcopybrief

**Comment by tsutaj** [comment]
現状は `@brief` に書かれているものは全部箇条書きで出力されるのですが、
* 最初に出てきた `@brief` はタイトルに使う
* それ以外の `@brief` は箇条書き
でよろしいですか？

**Comment by kmyk** [comment]
よさそうです。
ところで `@title` や `@file` は残しますか？ 消してしまってもよいですが、下のようにしてもいいかなと思ってました。

1. `@title` か `@file` があればそれを使う (現状と同じ)
2. `@title` か `@file` がなく `@brief` があれば一番上のものを使う
3. なにもなければファイル名を使う (現状と同じ)

**Comment by tsutaj** [comment]
よさそう 書いてみました https://github.com/kmyk/online-judge-verify-helper/commit/9b80f4e1ee136eafda1ea5d023fb79d0474c4701
`@file` は本家 Doxygen にもあるのですが、若干意味違いそう (あくまでファイル名を指定しているだけであり、タイトルではない) ので対象から消しました

**Comment by tsutaj** [comment]
![Screenshot at 2019-12-09 18-34-08](https://user-images.githubusercontent.com/19629946/70424424-bb792100-1ab2-11ea-9f6f-ac4a61d148b8.png)

リンク壊れた なおします

**Comment by kmyk** [comment]
ここ https://kmyk.github.io/online-judge-verify-helper/ と私のライブラリの上では動いてます

**Comment by tsutaj** [comment]
http://kmyk.github.io/competitive-programming-library/ でもリンクが壊れているように見えます (先程の画像のところです)
ちょっといま時間がないのでとりあえず `[` と `]` だけエスケープさせて push しました (Markdown 記法用のエスケープ方法、何かいい方法あるのでしょうか？)

**Comment by kmyk** [comment]
Markdown のエスケープはかなり難しいです。仕様が曖昧なので
HTML の中だと Markdown として解釈されなくなることが多いので問題の部分をすべて HMLT で書いてしまう(`[XXX](YYY)` を `<a href="YYY">XXX</a>` にするとか) と回避できることが多いです (それでもたまにだめですが)

**Comment by tsutaj** [comment]
たしかに、直 HTML にしたら `"` のエスケープだけで済みそう？？
直していきます

**Comment by tsutaj** [comment]
![Screenshot at 2019-12-10 09-16-11](https://user-images.githubusercontent.com/19629946/70484008-c329db80-1b2d-11ea-95bd-22a971502810.png)

なおった
