### ISSUE TITLE
yosupoジャッジのcheckerを見てしまっている？

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#36]
FileNotFoundError: /home/runner/work/library/library/.verify-helper/0925834712fe4ff496be047434267932/testlib.h seems not to exist in path_to_verification

https://pipelines.actions.githubusercontent.com/assX3GCC0bgrIX6HB9SG6MgtUTFQ7Nyl5vOQ8OimnHInAUObpJ/_apis/pipelines/1/runs/381/signedlogcontent/3?urlExpires=2019-12-09T15%3A03%3A39.8134261Z&urlSigningMethod=HMACV1&urlSignature=EjSM%2FkvGkYCmD0J1EwflmQvLCv1b0W4uuLnRzNvcIfI%3D

https://github.com/kmyk/online-judge-verify-helper/blob/0b3767a75fa686491da2cf304d452078d43f5939/onlinejudge_verify/docs.py#L468
で.verify-helper以下は除くべきな気がします

**Comment by tsutaj** [comment]
https://github.com/beet-aizu/library/commit/247b8a79dd501f1c4e3e30b506253aecb1a97846 で落ちている問題のことですかね、リポジトリ内にある test ファイルの中で yosupo judge の checker を使用しているものが具体的にどれなのか教えていただけますか？手元でいろいろ確認したいので

`docs.py` の実装見直してみてたんですが、`.verify-helper` を除外していないのと、 `#include "hoge"` されているものが全部 Docs 生成の対象となる前提でコードが組まれていてよろしくないですね。なおします

**Comment by tsutaj** [comment]
とりあえずいろいろ直した

* パスに `.verify-helper` が含まれているものは無視
* 無視すべきファイルを `#include` していても Dependencies や Required などに表示させない

また試してみてください

**Comment by beet-aizu** [comment]
あーごめんなさい　yosupoジャッジの問題は全部checkerを使っています

**Comment by tsutaj** [comment]
* yosupo ジャッジを `test` するときはテストケースだけではなく checker の `cpp` ファイルもダウンロードされる
* ダウンロードされた `cpp` ファイルは `.verify-helper` の中に入る
* checker は push されない (`.gitignore かなにかで ignore される)
* (エラーが発生したのは手元に生成された checker の `cpp` ファイルもビルド対象となってしまったのが原因)
で、あってますか？

**Comment by beet-aizu** [comment]
はい、あっています。

**Comment by beet-aizu** [comment]
ビルド通りました！

**Comment by tsutaj** [comment]
やったぜ
