### ISSUE TITLE
unmark verified

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#4]
https://github.com/kmyk/online-judge-verify-helper/issues/1#issuecomment-559058595

**Comment by beet-aizu** [comment]
こんな感じかなあ　文字列作るのがめんどくさい感はある
https://github.com/beet-aizu/library/blob/master/test/unmark.py

**Comment by beet-aizu** [comment]
最後にverifyが走ったのがいつかを知りたくなること、あるか？あるかも（timestampに文字列で保存したい）

**Comment by kmyk** [comment]
ありそう
雑にファイルを作ってるけど `test/timestamp/036a67ff64c716b2a7c74511ce88175a` って何ですか？？？って感じでかなり使い勝手悪いし、`timestamps.json` みたいなファイルに `{"test/segment_tree.yosupo.test.cpp": "2019-11-29T16:08:25+09:00", ...}`  みたいな形式でまとめて分かりやすく管理したい思いがある

**Comment by beet-aizu** [comment]
yosupo judgeのgeneratorのタイムスタンプも考慮に入れればいいかもしれない気がしてきました

**Comment by beet-aizu** [comment]
これはまあ割とすぐにできるんですがコマンド名何がいいですかね

**Comment by kmyk** [comment]
コマンドにしなくてもよい気がしています。どうですか @beet-aizu 
「json を編集してください」って書いて終わりにするのが楽そう。メンテするにあたってコードは少なければ少ないほどよいので、コードを増やさずに済ませられるならそうしたい

**Comment by beet-aizu** [comment]
確かに〜〜（読める形式になったならユーザーが好き勝手できますね）
