### ISSUE TITLE
Copyボタンを押したときにincludeを展開してクリップボードにコピーする

### ISSUE THREAD

**Issue by kyuridenamida** [kmyk/online-judge-verify-helper#43]
Copyボタンを押したときにincludeを展開してクリップボードにコピーする cc @kmyk

**Comment by kmyk** [comment]
利便性だけでなく bundle 機能の導線としても優秀なのでぜひやりたい
ref #44

**Comment by kmyk** [comment]
「そのまま表示 / include を展開した結果を表示」みたいなトグルボタン + それに対応したコピーボタン、に分けて用意したさある

**Comment by kmyk** [comment]
実装した 💪
