### ISSUE TITLE
GITHUB_TOKEN が timeout する問題

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#51]
現状: とりあえず 10 分で実行を打ち切ってる

- ドキュメントは 60 分で token が失行って言ってる
- 高速化 #49 が済めば気にならなくなるはず
- Personal Access Token は失行しないのでこれを使えば解決するけど、うっかりで無限ループしたときがこわいので避けたい
- いまは @beet-aizu しか困ってない

**Comment by beet-aizu** [comment]
困っています　僕が

**Comment by beet-aizu** [comment]
これの打ち切る時間もオプションで設定できるようにしたいです（します）

**Comment by beet-aizu** [comment]
#155 で対応
