### ISSUE TITLE
なんで動いているのかわからない

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#54]
https://github.com/kmyk/online-judge-verify-helper/blob/de96ec3b50a5b5557ddf9ef808b0d20c22a4a10e/data/test.sh#L102

g++でmark-verifiedが走ったらその後のclang++ではis-verifiedがTrueになっている気がするが、ログを見る限り動いている（なんで？

**Comment by beet-aizu** [comment]
@kmyk

**Comment by kmyk** [comment]
verify の timestamp にコンパイラの情報も含めてるから (だめな仕様) だと思います。

https://github.com/kmyk/online-judge-verify-helper/blob/de96ec3b50a5b5557ddf9ef808b0d20c22a4a10e/data/test.sh#L41

**Comment by beet-aizu** [comment]
そうでした！ありがとうございます
