### ISSUE TITLE
URLないやつはいらないと思う

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#55]
https://github.com/kmyk/online-judge-verify-helper/blob/de96ec3b50a5b5557ddf9ef808b0d20c22a4a10e/data/test.sh#L77

混乱の元だし消したい

**Comment by kmyk** [comment]
混乱の元、分かる。Python での書き直しが終わるまではとりあえず消してもよさそう
しかし、テスト用の問題が見当たらないときに入力をランダム生成して愚直解と比較するやつ ([例](https://kmyk.github.io/competitive-programming-library/verify/data_structure/sliding_window_aggregation.test.cpp.html)) をするのに使える仕組みは、後ででもよいのでなにか代わりに用意したい

**Comment by beet-aizu** [comment]
テスト用の問題が見当たらなかったら、yosupoジャッジにプルリクを投げるべきだろ

**Comment by kmyk** [comment]
:innocent:

**Comment by kmyk** [comment]
> テスト用の問題が見当たらなかったら、yosupoジャッジにプルリクを投げるべきだろ

よく考えたらこれかなり正しいな
