### ISSUE TITLE
失敗してもそれまでの時点の verify 結果を保存するように

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#59]
したくない？

**Comment by beet-aizu** [comment]
actionsで✅ついてるのに失敗してたら、ダメだろ（メールこなくなるし

**Comment by kmyk** [comment]
verify commit した後に自爆すれば ❌ は付くはず

**Comment by beet-aizu** [comment]
かしこい！！！（それはどうなんだ？）　実装お願いします 🙇

**Comment by kmyk** [comment]
試してみます :ok_hand:

**Comment by kmyk** [comment]
成功した。commit はされるけどちゃんと表示は赤くなってくれた

**Comment by beet-aizu** [comment]
落ちたらドキュメントの方のアイコンも ❌ にしたくないですか？

**Comment by kmyk** [comment]
したい
@tsutaj
