### ISSUE TITLE
バンドル機能のオンオフ

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#67]
どうせ僕のバンドルは通りようがないので　少しでもビルドを早くするためにオフにしたい

**Comment by kmyk** [comment]
オフにしても高々1.1倍速ぐらいにしかならないはずです。そんな誤差程度の改善でなくて、どうせやるなら cache action (2倍速以上) の安定化とか yosupo.judge.jp の問題生成のキャッシュ (2倍速ぐらい？) とか並列化 (20倍速) みたいなちゃんと速くなってかつみんながうれしいやつに開発力を使ってほしいです
