### ISSUE TITLE
I would like to try to make an emacs client for this

### ISSUE THREAD

**Issue by jasonsun0310** [kmyk/online-judge-verify-helper#72]
also, I might want to modify the bundle.py to work with `using` keyword instead of `include`. This could be better because `using algo::graph::maxflow` might look better than `include "algo/graph/maxflow" because the former one could provide real namespace separation thus rendering code more modular.

**Comment by kmyk** [comment]
Thank you for making an issue :smile:
By the way, please make two issues when you want to suggest two things (for details, read other documents like https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f )

##  Emacs client

Making clients is welcome.
However, we (at least, I) don't want to maintain such an editor-specific client.
Please make it in your own repository or tell us how valuable it is.

##  `bundle.py` with `using`

I couldn't understand what you are saying with `using` keyword.
`using algo::graph::maxflow;` enables you refer to `algo::graph::maxflow::foo` with just `foo`, but do nothing more than this. This isn't related to modularity. You need to include a header file containing `algo::graph::maxflow::foo` even if you use `using algo::graph::maxflow;`.

Did you make a typo with `import` keyword introduced in C++20?
Or, do you say about the categorizing feature of `docs.py` and `namespace`?

**Comment by jasonsun0310** [comment]
I agree with your point on emacs. I don’t plan to make it to the trunk but more of as an extension. Reason for this is because emacs has a bunch of good plugins that might introduce some improvements. 

With regard to using keywords I have something else in mind, it is quite hard to explain. Perhaps I can demonstrate it to you via a minimal working example once(if) I got it to work. Basically it would mimic the bare bone functionality of Chelper. But without the heavy usage of IDE or cmake. There are currently two cpp variant for this but they are all either too heavy( uses CLion or VS) not well maintained. 

I looked up the documentation for import in c20 I currently am a bit confusedabout the specifics of it. But I suppose it might be similar to what I have in mind.

**Comment by jasonsun0310** [comment]
Ohhh, btw Merry Christmas from New York. 

(A little fun fact I just learnt yesterday: one of the very few museums( perhaps the only one) that remains open on Christmas  day in NYC is the museum of Mathematic. LOL. )

**Comment by kmyk** [comment]
## Emacs client

I see. By the way, although I said I don't maintain your plugin, of course I help you if you have any trouble :+1:

## `bundle.py` with `using`

Then, do you mean something like adding `#include` directives automatically (e.g. https://github.com/syohex/emacs-cpp-auto-include )?

If this is so, I think it's a good feature (actually, I'm going to make such a tool some day) but I would like to develop as a separate project. Because this online-judge-verify-helper is a tool to verify, and auto-include is not a tool related to verify. I feel that it's rather a tool about formatting and linting. As Unix philosophy saying, each program should do only one thing,

**Comment by jasonsun0310** [comment]
Thanks! 

**bundle.py with using.**

Yes, it is auto include with fancier functionalities. To put it abstractly, I want to build a map F that build a one-to-one(in an ideal world...) between the space  multi-file solution draft with library with include directive or using directive and the space of submittable solution to the major online judges and at the same time minimizes the number of unused library code being carried over.
An example: suppose we have 
```c++
namespace algo::graph {
struct bellman_ford {};
struct floyd_warshall {};

template <typename T> distance();

template <>
decltype(auto) distance<bellman_ford>(abstract_graph g, abstract_vertex from, abstract_vertex to) {
...impl...
}

template <>
decltype(auto) distance<floyd_warshall>(abstract_graph g, abstract_vertex from, abstract_vertex to) {
...impl...
}
}
```

in my local solution I have 
```c++
int main() {
  using algo::graph::distance;
  auto solution = [&] {
  ...
  auto answer = distance<floyd_warshall>(u, v);
  ...
  }
}

```
Then I would only want the generated submittable file to include all the other non-related algos in the same namespace such as `distance<bellmam_ford>`. Although this example is quite trivial, but I think it shall demonstrate what my goal is.

**Comment by kmyk** [comment]
### `bundle.py` with `using`

I understood your suggestion. I agree that there is the aesthetical issue, but again I feel this is not in responsibility of this tool.

---

By the way, I recommend that you split the feature you want into 3 independent parts:

1.  insert auto include (possibly an editor plugin)
1.  expand include (`bundle.py`)
1.  erase dead code (auto-fix feature of a linter)

All of these are valuable and I want to encourage you to implement these as your own program.
