### ISSUE TITLE
checker.cpp のコンパイルを Library Checker の generate.py に任せる

### ISSUE THREAD

**Issue by kmyk** [kmyk/online-judge-verify-helper#97]
現状はたいてい `testlib.h` しか include しないし C++ の環境問題も制御されてるので雑にやってなんとかなってるが、どうみてもそのうち壊れるケースがでてくる。ひとまずの対応として `--sol` ってしてもいいけど、できれば `generate.py` に `--compile-checker` みたいなオプションがほしい

https://github.com/kmyk/online-judge-verify-helper/blob/f0288633ac57f278640bfebbb066c3a91713fc19/onlinejudge_verify/verify.py#L66-L93

cc: @yosupo06

**Comment by kmyk** [comment]
online-judge-tools の方で、verify helper にのみ影響するような破壊的変更 https://github.com/kmyk/online-judge-tools/pull/671 をしています。破壊的変更なので、そのままだと動かなくなります。online-judge-tools が更新されたら同時に対応する必要があります

次のあたりをごっそり消して、`download_checker_binary()` を使うようにすればよいです。

https://github.com/kmyk/online-judge-verify-helper/blob/9ebd7e841d57941cdf582371941e3175c25a8066/onlinejudge_verify/verify.py#L74

**Comment by beet-aizu** [comment]
これ閉じていいですか

**Comment by kmyk** [comment]
OK
