### ISSUE TITLE
no-push オプションの追加

### ISSUE THREAD

**Issue by beet-aizu** [kmyk/online-judge-verify-helper#99]
CXXFLAGSに-D_GLIBCXX_DEBUGとか-fsanitize=undefinedとかをつけて同時にverifyをしたい。
この場合はpushはしないでおきたいのでオプションを追加したい
あるいはpush先のブランチを指定できるようにしてもいいかもしれない

**Comment by kmyk** [comment]
`$GITHUB_TOKEN` とか `$GITHUB_ACTION` みたいな環境変数を見て push するかどうか決める実装だから、これらの環境変数を消せば push はされません
オプションを足してもいいけど、ドキュメントを書いて済ませた方が楽そう

**Comment by beet-aizu** [comment]
ドキュメント書きます

**Comment by beet-aizu** [comment]
pushされません（keyErrorで落ちるので）
https://github.com/beet-aizu/library/actions/runs/32042149

**Comment by beet-aizu** [comment]
https://github.com/kmyk/online-judge-verify-helper/blob/f0288633ac57f278640bfebbb066c3a91713fc19/onlinejudge_verify/main.py#L92
GH-PATは必要そう

**Comment by beet-aizu** [comment]
ん、違うな　GH_PATがないときはGITHUB_TOKENが存在することを仮定していないか

**Comment by beet-aizu** [comment]
https://github.com/kmyk/online-judge-verify-helper/blob/f0288633ac57f278640bfebbb066c3a91713fc19/onlinejudge_verify/main.py#L47
GITHUB_ACTIONって上書きできるんか…？　まあやってみます

**Comment by beet-aizu** [comment]
なんかこういう環境変数（GITHUB_*）とかって書き換えない方がいい気がするんですけど

**Comment by beet-aizu** [comment]
そもそも書き換えられないっぽい　https://github.com/beet-aizu/library/actions/runs/32046148

**Comment by kmyk** [comment]
@beet-aizu `env -U oj-verify run` して
https://linuxjm.osdn.jp/html/GNU_sh-utils/man1/env.1.html

**Comment by kmyk** [comment]
`GITHUB_TOKEN` を `verify.yml` から消して `GITHUB_ACTION` を渡さず実行 (`env -u GITHUB_ACTION oj-verify run`) が正解かな
https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token

**Comment by beet-aizu** [comment]
verify.yml ではGH_PATとGITHUB_TOKEN両方必要そうですけど

**Comment by kmyk** [comment]
必要ではないです

いま我々は push されないようにしたいです。ローカルで実行した場合は当然 push されません。なのでローカルでの実行と同じ状況を作ればよい。つまり `GITHUB_*` が何も定義されていない状態にすればよくて、 `GITHUB_ACTION` も `GITHUB_TOKEN` も `GH_PAT` も全部消してください。それで解決します

**Comment by beet-aizu** [comment]
あーごめんなさい、verify.yml は残した上で sanitize.yml を新しく作ったんですが、そのことを共有していませんでした

**Comment by beet-aizu** [comment]
ところで timestamps.local.json を見てしまうのとtimeoutがinfになってしまうのがあるので env -u GITHUB_REF oj-verify run にします

**Comment by beet-aizu** [comment]
動いたっぽい　了解！

**Comment by kmyk** [comment]
:tada:

**Comment by kmyk** [comment]
`env -u GITHUB_REF oj-verify run` より #104 の方が実装として適切なのでプルリク出しておきました
